import Script from "next/script";

export default function Head({title}: { title?: string }) {
    return (
        <>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <title>{title}</title>
            <link rel="icon" type="image/png"/>
            <Script async src="https://www.googletagmanager.com/gtag/js?id=UA-129374877-1"/>
            <Script id="gtag" strategy="afterInteractive" dangerouslySetInnerHTML={{
                __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','UA-129374877-1');`
            }}/>
            {/*<Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBKGek53j0LfkfDTUs5lh-clKfcPECMBZA"/>*/}
            <link rel="icon" href="/favicon.ico"/>
        </>
    )
}
